#######################################################################################
# Book settings
title                       : Accelerated gradient descent and related algorithms  # The title of the book. Will be placed in the left navbar.
author                      : Karthik Vijayakumar  # The author of the book
copyright                   : "2020"  # Copyright year to be placed in the footer
logo                        : 'gradient-ascent-logo.png'  # A path to the book logo

# Information about where the book exists on the web
description: >-
  A brief overview of accelerated gradient descent and related algorithms.

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : cache

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar         : false

# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"

#######################################################################################
# Launch button settings
# repository:
#   url                         : https://github.com/executablebooks/quantecon-mini-example
#   path_to_book                : "mini_book"

# binder:
#   binderhub_url               : "https://mybinder.org"
#   text                        : "Launch binder"

# latex:
#   latex_engine                : "xelatex"
#   latex_documents:
#     targetname: book.tex
